# Generated by Django 5.2.8 on 2025-11-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
